# version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: project-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
