name: Backend CI/CD

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: fasilu07/teamverse

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: team-varse

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 🐳 Build & push Docker image
        run: |
          docker build -t $IMAGE_NAME ./backend
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
